# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: 
date_format: "ordinal"
title: لاراول
subtitle: "مستندات فارسی لاراول"
description: "مستندات فارسی لاراول"
keywords: لاراول, laravel, داکیومنت لاراول, لاراول فارسی
timezone: Asia/Tehran
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Hossein Moghadam
organization: hossein-moghadam.ir
organization_url: http://www.hossein-moghadam.ir
github_username: hosseinmoghaddam
location: ایران , کرج
email: hosseinghmoghadam@gmail.com

# # ---------------- #
# #    Navigation    #
# # ---------------- #
# navs:

#   -
#     href: /home
#     label: خانه

#   -
#     href: /categories/
#     label: دسته ها

#   -
#     href: /live/
#     label: پخش زنده

# #  -
# #    href: /wiki/
# #    label: ویکی

#   -
#     href: /donate/
#     label: حمایت

#   -
#     href: /about/
#     label: درباره

#   - href: /
#     label: رزومه


# # ---------------- #
# #       RSS        #
# # ---------------- #
# subscribe_rss: /feed.xml

# # ---------------- #
# #      Jekyll      #
# # ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
# paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll-mentions
# collections:
#     wiki:
#         output: true
#         permalink: /wiki/:path/

# repository: hosseinmoghaddam/hosseinmoghaddam.github.io

# # ---------------- #
# #      Comments    #
# # ---------------- #
# # support provider: disqus, gitment, gitalk
# comments_provider: gitalk
# # !!!重要!!! 请修改下面这些信息为你自己申请的
# # !!!Important!!! Please modify infos below to yours
# # https://disqus.com
# disqus:
#     username: 
# # https://imsun.net/posts/gitment-introduction/
# gitment:
#     owner: hosseinmoghaddam
#     repo: blog-comments
#     oauth:
#         client_id: 0a00412c3c5ed8ba1245
#         client_secret: f80c6c62624917a3c993afc2a56c9822e4614755
# # https://github.com/gitalk/gitalk#install
# gitalk:
#     owner: hosseinmoghaddam
#     repo: blog-comments
#     clientID: 0a00412c3c5ed8ba1245
#     clientSecret: f80c6c62624917a3c993afc2a56c9822e4614755
# # 在使用其它评论组件时可点击显示 Disqus
# lazy_load_disqus : false

# # ---------------- #
# #      Search      #
# # ---------------- #
# simple_jekyll_search:
#     # 是否支持全文搜索
#     fulltext: true
#     # 最多显示多少条搜索结果
#     limit: 10

# # ---------------- #
# #    Analytics     #
# # ---------------- #
# google:
#     analytics_id: UA-127816614-1
